spring.application.name=mathtutortable

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tutordb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tutoruser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tutorpass}
